/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mohamed
 */
import java.util.*;
import  java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.sun.jdi.connect.spi.Connection;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import java.time.LocalDateTime;  
import java.time.format.DateTimeFormatter;  
public class Member_page extends javax.swing.JFrame {
    
            Stack<Integer>stk = new Stack<>();
            
            int value_back;
                     java.sql.Connection c;
                      java.sql.Connection getdata;

                      PreparedStatement p;

            
          Boolean flag_list = true;
                    Boolean flag_delet = true;

                
               
           
             

   
    
    /**
     * Creates new form Member_page
     */
    public Member_page() {
        initComponents();
        stk.push(0);
        //ShowData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        Back_Member_page_btn = new javax.swing.JButton();
        Add_Member_page_btn = new javax.swing.JButton();
        Search_Member_page_btn = new javax.swing.JButton();
        Delet_Member_page_btn = new javax.swing.JButton();
        Update_Member_page_btn = new javax.swing.JButton();
        List_Member_page_btn = new javax.swing.JButton();
        Report_Member_page_btn = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Add_Member_page_panel = new javax.swing.JPanel();
        Member_FirstName_Add = new javax.swing.JTextField();
        Member_LastName_Add = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Submit_Add = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Member_id_add = new javax.swing.JTextField();
        Member_Email_Add = new javax.swing.JTextField();
        Member_pass_add = new javax.swing.JTextField();
        Member_membership_add = new javax.swing.JTextField();
        Member_coachid_add = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Member_age_add = new javax.swing.JTextField();
        Member_sub_start = new javax.swing.JTextField();
        Member_sub_end = new javax.swing.JTextField();
        Search_Member_page_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        List_Member_page_panel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Table_List = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        Refresh_DB = new javax.swing.JButton();
        Update_Member_page_panel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        Update_id_search = new javax.swing.JTextField();
        Update_email_search = new javax.swing.JTextField();
        Update_pass_new = new javax.swing.JTextField();
        Update_sun_end_date_new = new javax.swing.JTextField();
        Update_coach_id_new = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Update_new_update = new javax.swing.JButton();
        Delet_Member_page_panel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        delet_member = new javax.swing.JButton();
        member_id_delet = new javax.swing.JTextField();
        Refresh_Delet_member = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        Table_List1 = new javax.swing.JTable();
        Report_Member_page_panel = new javax.swing.JPanel();
        send_report = new javax.swing.JButton();
        member_id_report_reciever = new javax.swing.JTextField();
        admin_id_report_sender = new javax.swing.JTextField();
        report_text = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(170, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(170, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(170, 600));

        Back_Member_page_btn.setText("Back");
        Back_Member_page_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_Member_page_btnActionPerformed(evt);
            }
        });

        Add_Member_page_btn.setText("Add");
        Add_Member_page_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_Member_page_btnActionPerformed(evt);
            }
        });

        Search_Member_page_btn.setText("Search");
        Search_Member_page_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_Member_page_btnActionPerformed(evt);
            }
        });

        Delet_Member_page_btn.setText("Delet");
        Delet_Member_page_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delet_Member_page_btnActionPerformed(evt);
            }
        });

        Update_Member_page_btn.setText("Update");
        Update_Member_page_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_Member_page_btnActionPerformed(evt);
            }
        });

        List_Member_page_btn.setText("List");
        List_Member_page_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                List_Member_page_btnActionPerformed(evt);
            }
        });

        Report_Member_page_btn.setText("Report");
        Report_Member_page_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Report_Member_page_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Update_Member_page_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delet_Member_page_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(List_Member_page_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search_Member_page_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Report_Member_page_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Back_Member_page_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add_Member_page_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(Add_Member_page_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Search_Member_page_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(List_Member_page_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(Update_Member_page_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(Delet_Member_page_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(Report_Member_page_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(Back_Member_page_btn)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Member_FirstName_Add.setText("fname");

        Member_LastName_Add.setText("sname");

        jLabel3.setText("jLabel3");

        jLabel7.setText("jLabel7");

        jLabel8.setText("jLabel8");

        jLabel9.setText("jLabel9");

        jLabel10.setText("jLabel10");

        jLabel11.setText("jLabel11");

        Submit_Add.setText("jButton1");
        Submit_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_AddActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        Member_id_add.setText("id");

        Member_Email_Add.setText("email");

        Member_pass_add.setText("pass");
        Member_pass_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Member_pass_addActionPerformed(evt);
            }
        });

        Member_membership_add.setText("memship");

        Member_coachid_add.setText("caochid");

        jLabel12.setText("jLabel12");

        Member_age_add.setText("age");

        Member_sub_start.setText("jTextField1");

        Member_sub_end.setText("jTextField1");
        Member_sub_end.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Member_sub_endActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Add_Member_page_panelLayout = new javax.swing.GroupLayout(Add_Member_page_panel);
        Add_Member_page_panel.setLayout(Add_Member_page_panelLayout);
        Add_Member_page_panelLayout.setHorizontalGroup(
            Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Add_Member_page_panelLayout.createSequentialGroup()
                .addGroup(Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Add_Member_page_panelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel3))
                            .addGap(63, 63, 63))
                        .addGroup(Add_Member_page_panelLayout.createSequentialGroup()
                            .addGap(132, 132, 132)
                            .addGroup(Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel7)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)
                                .addGroup(Add_Member_page_panelLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(55, 55, 55)
                                    .addComponent(Member_id_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(Add_Member_page_panelLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel12)
                        .addGap(129, 129, 129)))
                .addGroup(Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Member_age_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Add_Member_page_panelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Member_membership_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Member_pass_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Member_coachid_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Member_LastName_Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Member_FirstName_Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Member_Email_Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Add_Member_page_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Add_Member_page_panelLayout.createSequentialGroup()
                        .addComponent(Submit_Add)
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Add_Member_page_panelLayout.createSequentialGroup()
                        .addGroup(Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Member_sub_end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Member_sub_start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))))
        );
        Add_Member_page_panelLayout.setVerticalGroup(
            Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Add_Member_page_panelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(Member_id_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Add_Member_page_panelLayout.createSequentialGroup()
                        .addGroup(Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Member_FirstName_Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(37, 37, 37)
                        .addComponent(Member_LastName_Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Member_Email_Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(Member_sub_start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(Member_pass_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(Member_sub_end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Member_membership_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Member_coachid_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(Add_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Member_age_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(Submit_Add)
                .addGap(40, 40, 40))
        );

        jTabbedPane1.addTab("tab1", Add_Member_page_panel);

        jLabel2.setText("search");

        javax.swing.GroupLayout Search_Member_page_panelLayout = new javax.swing.GroupLayout(Search_Member_page_panel);
        Search_Member_page_panel.setLayout(Search_Member_page_panelLayout);
        Search_Member_page_panelLayout.setHorizontalGroup(
            Search_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Search_Member_page_panelLayout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(jLabel2)
                .addContainerGap(414, Short.MAX_VALUE))
        );
        Search_Member_page_panelLayout.setVerticalGroup(
            Search_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Search_Member_page_panelLayout.createSequentialGroup()
                .addContainerGap(321, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(272, 272, 272))
        );

        jTabbedPane1.addTab("tab2", Search_Member_page_panel);

        Table_List.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Second Name", "Id", "Subscription_End_Date", "Coach Id"
            }
        ));
        jScrollPane3.setViewportView(Table_List);

        jLabel6.setText("jLabel6");

        Refresh_DB.setText("jButton1");
        Refresh_DB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Refresh_DBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout List_Member_page_panelLayout = new javax.swing.GroupLayout(List_Member_page_panel);
        List_Member_page_panel.setLayout(List_Member_page_panelLayout);
        List_Member_page_panelLayout.setHorizontalGroup(
            List_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(List_Member_page_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(List_Member_page_panelLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Refresh_DB)
                .addGap(233, 233, 233))
        );
        List_Member_page_panelLayout.setVerticalGroup(
            List_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, List_Member_page_panelLayout.createSequentialGroup()
                .addGap(0, 58, Short.MAX_VALUE)
                .addGroup(List_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Refresh_DB)
                    .addComponent(jLabel6))
                .addGap(48, 48, 48)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("tab3", List_Member_page_panel);

        jLabel13.setText("jLabel13");

        Update_id_search.setText("id");

        Update_email_search.setText("email");

        Update_pass_new.setText("new pass");
        Update_pass_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_pass_newActionPerformed(evt);
            }
        });

        Update_sun_end_date_new.setText("new sub_end_date");

        Update_coach_id_new.setText("new coach_id");
        Update_coach_id_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_coach_id_newActionPerformed(evt);
            }
        });

        jLabel4.setText("jLabel4");

        jLabel14.setText("jLabel14");

        jLabel15.setText("jLabel15");

        Update_new_update.setText("jButton1");
        Update_new_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_new_updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Update_Member_page_panelLayout = new javax.swing.GroupLayout(Update_Member_page_panel);
        Update_Member_page_panel.setLayout(Update_Member_page_panelLayout);
        Update_Member_page_panelLayout.setHorizontalGroup(
            Update_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Update_Member_page_panelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(Update_id_search, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addComponent(Update_email_search, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
            .addGroup(Update_Member_page_panelLayout.createSequentialGroup()
                .addGroup(Update_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Update_Member_page_panelLayout.createSequentialGroup()
                        .addGroup(Update_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Update_Member_page_panelLayout.createSequentialGroup()
                                .addGroup(Update_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Update_Member_page_panelLayout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(jLabel13))
                                    .addGroup(Update_Member_page_panelLayout.createSequentialGroup()
                                        .addGap(110, 110, 110)
                                        .addComponent(jLabel14)))
                                .addGap(124, 124, 124))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Update_Member_page_panelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(Update_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Update_Member_page_panelLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(91, 91, 91))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Update_Member_page_panelLayout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(109, 109, 109)))))
                        .addGroup(Update_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Update_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Update_sun_end_date_new, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                .addComponent(Update_pass_new))
                            .addComponent(Update_coach_id_new, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Update_Member_page_panelLayout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(Update_new_update)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Update_Member_page_panelLayout.setVerticalGroup(
            Update_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Update_Member_page_panelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(Update_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Update_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(Update_coach_id_new, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Update_Member_page_panelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addGroup(Update_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Update_Member_page_panelLayout.createSequentialGroup()
                                .addGroup(Update_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Update_id_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Update_email_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(61, 61, 61)
                                .addGroup(Update_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Update_pass_new, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(55, 55, 55)
                                .addComponent(Update_sun_end_date_new, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel14))
                        .addGap(73, 73, 73)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addComponent(Update_new_update)
                .addGap(88, 88, 88))
        );

        jTabbedPane1.addTab("tab4", Update_Member_page_panel);

        jLabel5.setText("jLabel5");

        delet_member.setText("jButton1");
        delet_member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delet_memberActionPerformed(evt);
            }
        });

        member_id_delet.setText("jTextField1");

        Refresh_Delet_member.setText("refresh");
        Refresh_Delet_member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Refresh_Delet_memberActionPerformed(evt);
            }
        });

        Table_List1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Second Name", "Id", "Subscription_End_Date", "Coach Id"
            }
        ));
        jScrollPane5.setViewportView(Table_List1);

        javax.swing.GroupLayout Delet_Member_page_panelLayout = new javax.swing.GroupLayout(Delet_Member_page_panel);
        Delet_Member_page_panel.setLayout(Delet_Member_page_panelLayout);
        Delet_Member_page_panelLayout.setHorizontalGroup(
            Delet_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Delet_Member_page_panelLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel5)
                .addGap(167, 167, 167)
                .addComponent(member_id_delet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Refresh_Delet_member)
                .addGap(126, 126, 126))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Delet_Member_page_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(Delet_Member_page_panelLayout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(delet_member)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Delet_Member_page_panelLayout.setVerticalGroup(
            Delet_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Delet_Member_page_panelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(Delet_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(member_id_delet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Refresh_Delet_member))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(delet_member))
        );

        jTabbedPane1.addTab("tab5", Delet_Member_page_panel);

        send_report.setText("jButton1");
        send_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_reportActionPerformed(evt);
            }
        });

        member_id_report_reciever.setText("jTextField1");

        admin_id_report_sender.setText("jTextField2");
        admin_id_report_sender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_id_report_senderActionPerformed(evt);
            }
        });

        report_text.setText("jTextField3");

        javax.swing.GroupLayout Report_Member_page_panelLayout = new javax.swing.GroupLayout(Report_Member_page_panel);
        Report_Member_page_panel.setLayout(Report_Member_page_panelLayout);
        Report_Member_page_panelLayout.setHorizontalGroup(
            Report_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Report_Member_page_panelLayout.createSequentialGroup()
                .addGroup(Report_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Report_Member_page_panelLayout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(send_report))
                    .addGroup(Report_Member_page_panelLayout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addGroup(Report_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(member_id_report_reciever, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(report_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Report_Member_page_panelLayout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(admin_id_report_sender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(337, Short.MAX_VALUE))
        );
        Report_Member_page_panelLayout.setVerticalGroup(
            Report_Member_page_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Report_Member_page_panelLayout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(admin_id_report_sender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(member_id_report_reciever, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(report_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(send_report)
                .addGap(168, 168, 168))
        );

        jTabbedPane1.addTab("tab6", Report_Member_page_panel);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, -39, 730, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Back_Member_page_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_Member_page_btnActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == Back_Member_page_btn){
            try{
 
             value_back = stk.peek();
            }catch(EmptyStackException  ex){
                System.out.println(ex);
            }
           try{
               
               value_back = stk.pop();
              
           }catch(Exception e){
            System.out.println(e);
            
        }finally{
         jTabbedPane1.setSelectedIndex(value_back);
  
           }
           
       
        }
    }//GEN-LAST:event_Back_Member_page_btnActionPerformed

   
    private void Delet_Member_page_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delet_Member_page_btnActionPerformed
        if(evt.getSource() == Delet_Member_page_btn){
            jTabbedPane1.setSelectedIndex(4);
            stk.push(4);
             if(flag_delet == true){
                show_delet_table();
                flag_delet = false;
                }
          
        }
                     

    }//GEN-LAST:event_Delet_Member_page_btnActionPerformed

    private void List_Member_page_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_List_Member_page_btnActionPerformed
         if(evt.getSource() == List_Member_page_btn){
                jTabbedPane1.setSelectedIndex(2);
                stk.push(2);
                if(flag_list == true){
                ShowData();
                flag_list = false;
                }
                
        }
    }//GEN-LAST:event_List_Member_page_btnActionPerformed

    private void Add_Member_page_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_Member_page_btnActionPerformed
        if(evt.getSource() == Add_Member_page_btn){
        jTabbedPane1.setSelectedIndex(0);
        stk.push(0);
        // create connection
       
          
          
            
            
        
        }
    }//GEN-LAST:event_Add_Member_page_btnActionPerformed

    private void Search_Member_page_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_Member_page_btnActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == Search_Member_page_btn){
                jTabbedPane1.setSelectedIndex(1);
                stk.push(1);
        }

    }//GEN-LAST:event_Search_Member_page_btnActionPerformed

    private void Update_Member_page_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_Member_page_btnActionPerformed
         if(evt.getSource() == Update_Member_page_btn){
                jTabbedPane1.setSelectedIndex(3);
                stk.push(3);
        }

    }//GEN-LAST:event_Update_Member_page_btnActionPerformed

    private void Report_Member_page_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Report_Member_page_btnActionPerformed
        // TODO add your handling code here:
         if(evt.getSource() == Report_Member_page_btn){
             stk.push(5);
                jTabbedPane1.setSelectedIndex(5);
                
        }
                    

    }//GEN-LAST:event_Report_Member_page_btnActionPerformed

    private void Submit_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_AddActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == Submit_Add){
         try {
                 
            c = DriverManager.getConnection("jdbc:mysql://localhost/GYM_db ","root","");
            
        }catch(SQLException E){
            System.out.println(E);
            
                   
        }
          
        
       // create statement
           boolean check = false;
            try {
                String Fname = Member_FirstName_Add.getText();
                String Sname = Member_LastName_Add.getText();
                 String Email = Member_Email_Add.getText();
              int  membership = Integer.parseInt(Member_membership_add.getText());
                 int coachid =Integer.parseInt(Member_coachid_add.getText());
                String pass =Member_pass_add.getText();
                 int id =Integer.parseInt( Member_id_add.getText());
                 int age  = Integer.parseInt(Member_age_add.getText());
                 Date startDate =  Date.valueOf(   Member_sub_start.getText() );
                 Date endDate =Date.valueOf(Member_sub_end.getText());

                 
       
                java.sql.Statement  ss; 
            ss = c.createStatement();
            //create query
               //missed coach_id
                String query = "insert into member (member_id,member_firstName,member_lastName,member_subscription,member_email,member_password,member_age,member_subscription_startDate ,member_subscription_endDate ,member_coachId)values(' "+id+" ' ,' " +Fname+" ' ,' " +Sname+ " ',  ' " +membership+ " ',' " +Email+ " ',' " +pass+ " ' ,' " +age+ " '  ,' " +startDate+" '  ,' "+endDate+" ',' "+coachid + " ')";
                ss.execute( query);
                
            } catch (Exception ex) {
                Logger.getLogger(Member_page.class.getName()).log(Level.SEVERE, null, ex);
                 JOptionPane.showMessageDialog(this,"Fail");
                 check = true;
            }
                        if(!check){
                             JOptionPane.showMessageDialog(this,"Member Added Successfully");
                             ClearFields();
                        }

            
            
        }
           // endof the method
    }//GEN-LAST:event_Submit_AddActionPerformed

    private void Member_pass_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Member_pass_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Member_pass_addActionPerformed

    private void Member_sub_endActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Member_sub_endActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Member_sub_endActionPerformed

    private void Update_coach_id_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_coach_id_newActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Update_coach_id_newActionPerformed

    private void Update_new_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_new_updateActionPerformed
                try {
                                        c = DriverManager.getConnection("jdbc:mysql://localhost/GYM_db ","root","");

                    String id_search = Update_id_search.getText();
                    int id_search_int = Integer.parseInt(id_search);
                    String new_pass = Update_pass_new.getText();
                    int new_coach =  Integer.parseInt(Update_coach_id_new.getText());
                    String new_end = Update_sun_end_date_new.getText();
                    Date new_end_date = Date.valueOf(new_end);
                    if(Update_email_search.getText().equals("")&&Update_id_search.getText().equals("")&&Update_sun_end_date_new.getText().equals("")){ JOptionPane.showMessageDialog(this,"Fail\n complete all fields");}
                    if(!Update_pass_new.getText().equals("")){
                                        String query = "update member set  member_password = ' " +new_pass+" '  where member_id = ' " +id_search_int+" ' ";
                                           java.sql.Statement ss = c.createStatement();
                                         ss.execute(query);
                    }
                   
                    if(!Update_coach_id_new.getText().equals("")){
                        String  query = " update member set member_coachId = ' " +new_coach+" ' where member_id =' " +id_search_int+ " ' ";
                        java.sql.Statement ss = c.createStatement();
                        ss.execute(query);
                    }
                    
                    if(!Update_sun_end_date_new.getText().equals("")){
                          String  query = " update member set member_coachId = ' " +new_end_date+" ' where member_id =' " +id_search_int+ " ' ";
                        java.sql.Statement ss = c.createStatement();
                        ss.execute(query);
                    }
                 
                   
                    // System.out.println(id_search);
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Member_page.class.getName()).log(Level.SEVERE, null, ex);
                    System.out.println( ex);
                }
               
             
       
        
    }//GEN-LAST:event_Update_new_updateActionPerformed

    private void Update_pass_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_pass_newActionPerformed
           
    }//GEN-LAST:event_Update_pass_newActionPerformed

            @SuppressWarnings("empty-statement")
    private void send_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_reportActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == send_report){
            boolean popup = true;
            try {
                c = DriverManager.getConnection("jdbc:mysql://localhost/GYM_db ","root","");
             String content = report_text.getText();
                String sender = admin_id_report_sender.getText();
                String receiver = member_id_report_reciever.getText();
                int senderId = Integer.parseInt(sender);
                System.out.println(senderId);
            String check = "select count(admin_id) as cnt from admin  where admin_id = ' " +senderId+" ' ";
           PreparedStatement p =c.prepareStatement(check);
              ResultSet rr = p.executeQuery();
              rr.next();
               // System.out.println(rr.getInt("cnt"));
                if(rr.getInt("cnt") > 0){
                  
                int recieverid = Integer.parseInt(receiver);
                Date current  = Date.valueOf( java.time.LocalDate.now());
                String query = " insert into  report values(' "+content+" ',' "+current+" ',' "+senderId+" ',' "+recieverid+" ' ) ";
                java.sql.Statement ss = c.createStatement();
                ss.execute(query);
                  JOptionPane.showMessageDialog(this,"Sent Successfully");
               }
                else{
                    JOptionPane.showMessageDialog(this,"Fail\n maybe invalid data");
                }
                
                 
               
            } catch (SQLException ex) {
                Logger.getLogger(Member_page.class.getName()).log(Level.SEVERE, null, ex);
                 JOptionPane.showMessageDialog(this,"Fail\n maybe invalid data");
                
            }
          
           

        }
    }//GEN-LAST:event_send_reportActionPerformed

    private void Refresh_DBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Refresh_DBActionPerformed
        // TODO add your handling code here:
        DefaultTableModel m = (DefaultTableModel) Table_List.getModel();
        m.setRowCount(0);
         
        ShowData();
    }//GEN-LAST:event_Refresh_DBActionPerformed

    private void Refresh_Delet_memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Refresh_Delet_memberActionPerformed
      
      DefaultTableModel t1 = (DefaultTableModel) Table_List1.getModel();
          t1.setRowCount(0);
          show_delet_table();
    }//GEN-LAST:event_Refresh_Delet_memberActionPerformed

    private void delet_memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delet_memberActionPerformed
         try {
                c = DriverManager.getConnection("jdbc:mysql://localhost/GYM_db ","root","");
             String content = report_text.getText();
        String Member_Id_delet = member_id_delet.getText();
        int member_id_delet = Integer.parseInt(Member_Id_delet);
        String query = "delete from member where member_id = ' "+member_id_delet+" ' ";
          java.sql.Statement ss = c.createStatement();
                ss.execute(query);
         }
        catch(Exception ex){
                System.out.println(ex);
                    JOptionPane.showMessageDialog(this,"Invalid Data");
                }
         JOptionPane.showMessageDialog(this,"Successfully Deleted");
    }//GEN-LAST:event_delet_memberActionPerformed

    private void admin_id_report_senderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_id_report_senderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_id_report_senderActionPerformed
// clear all add fields
    private void ClearFields(){
    Member_Email_Add.setText("");
    Member_FirstName_Add.setText("");
    Member_LastName_Add.setText("");
    Member_age_add.setText("");
    Member_coachid_add.setText("");
    Member_id_add.setText("");
    Member_membership_add.setText("");
        Member_pass_add.setText("");
}
    
    private  void ShowData(){
 ArrayList<Member_DataBase_Version>Data_Table = new ArrayList<>();
      

 try{
           c = DriverManager.getConnection("jdbc:mysql://localhost/GYM_db ","root","");
        p = c.prepareStatement("select * from member");
        ResultSet r = p.executeQuery();
        DefaultTableModel m = (DefaultTableModel) Table_List.getModel();
                DefaultTableModel t1 = (DefaultTableModel) Table_List1.getModel();

           Object[ ]row = new Object[5];
        while(r.next()){
            
//Member_DataBase_Version m1 = new Member_DataBase_Version(r.getString("member_firstName"),r.getString("member_lastName"),r.getInt("member_id"),r.getString("member_subscription_endDate "),r.getInt("member_coachId"));
Member_DataBase_Version m1 = new Member_DataBase_Version(r.getString("member_firstName"),r.getString("member_lastName"),r.getInt("member_id"),r.getDate("member_subscription_endDate"),r.getInt("member_coachId"));
            Data_Table.add(m1);
            
        }
        for(int i=0;i<Data_Table.size();i++){
          row[0] = Data_Table.get(i).fname;
      row[1] =  Data_Table.get(i).sname;
         row[2] =  Data_Table.get(i).id;
         row[3] =  Data_Table.get(i).Sub_End_Date;
      row[4] =  Data_Table.get(i).Coach_Id;
     

         m.addRow(row);
         

        }
       // ShowData();
        
        
       
 }catch(SQLException ex){
     System.out.println(ex);
     try {
         c.close();
     } catch (SQLException ex1) {
         Logger.getLogger(Member_page.class.getName()).log(Level.SEVERE, null, ex1);
     }
 }
 }
    private void  show_delet_table(){
         ArrayList<Member_DataBase_Version>Data_Table = new ArrayList<>();
      

 try{
           c = DriverManager.getConnection("jdbc:mysql://localhost/GYM_db ","root","");
        p = c.prepareStatement("select * from member");
        ResultSet r = p.executeQuery();
        
                DefaultTableModel t1 = (DefaultTableModel) Table_List1.getModel();

           Object[ ]row = new Object[5];
        while(r.next()){
            
//Member_DataBase_Version m1 = new Member_DataBase_Version(r.getString("member_firstName"),r.getString("member_lastName"),r.getInt("member_id"),r.getString("member_subscription_endDate "),r.getInt("member_coachId"));
Member_DataBase_Version m1 = new Member_DataBase_Version(r.getString("member_firstName"),r.getString("member_lastName"),r.getInt("member_id"),r.getDate("member_subscription_endDate"),r.getInt("member_coachId"));
            Data_Table.add(m1);
            
        }
        for(int i=0;i<Data_Table.size();i++){
          row[0] = Data_Table.get(i).fname;
      row[1] =  Data_Table.get(i).sname;
         row[2] =  Data_Table.get(i).id;
         row[3] =  Data_Table.get(i).Sub_End_Date;
      row[4] =  Data_Table.get(i).Coach_Id;
     

       
         t1.addRow(row);

        }
       // ShowData();
        
        
       
 }catch(SQLException ex){
     System.out.println(ex);
     try {
         c.close();
     } catch (SQLException ex1) {
         Logger.getLogger(Member_page.class.getName()).log(Level.SEVERE, null, ex1);
     }
 }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Member_page().setVisible(true);
               
              // ShowData();
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Member_page_btn;
    private javax.swing.JPanel Add_Member_page_panel;
    private javax.swing.JButton Back_Member_page_btn;
    private javax.swing.JButton Delet_Member_page_btn;
    private javax.swing.JPanel Delet_Member_page_panel;
    private javax.swing.JButton List_Member_page_btn;
    private javax.swing.JPanel List_Member_page_panel;
    private javax.swing.JTextField Member_Email_Add;
    private javax.swing.JTextField Member_FirstName_Add;
    private javax.swing.JTextField Member_LastName_Add;
    private javax.swing.JTextField Member_age_add;
    private javax.swing.JTextField Member_coachid_add;
    private javax.swing.JTextField Member_id_add;
    private javax.swing.JTextField Member_membership_add;
    private javax.swing.JTextField Member_pass_add;
    private javax.swing.JTextField Member_sub_end;
    private javax.swing.JTextField Member_sub_start;
    private javax.swing.JButton Refresh_DB;
    private javax.swing.JButton Refresh_Delet_member;
    private javax.swing.JButton Report_Member_page_btn;
    private javax.swing.JPanel Report_Member_page_panel;
    private javax.swing.JButton Search_Member_page_btn;
    private javax.swing.JPanel Search_Member_page_panel;
    private javax.swing.JButton Submit_Add;
    private javax.swing.JTable Table_List;
    private javax.swing.JTable Table_List1;
    private javax.swing.JButton Update_Member_page_btn;
    private javax.swing.JPanel Update_Member_page_panel;
    private javax.swing.JTextField Update_coach_id_new;
    private javax.swing.JTextField Update_email_search;
    private javax.swing.JTextField Update_id_search;
    private javax.swing.JButton Update_new_update;
    private javax.swing.JTextField Update_pass_new;
    private javax.swing.JTextField Update_sun_end_date_new;
    private javax.swing.JTextField admin_id_report_sender;
    private javax.swing.JButton delet_member;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField member_id_delet;
    private javax.swing.JTextField member_id_report_reciever;
    private javax.swing.JTextField report_text;
    private javax.swing.JButton send_report;
    // End of variables declaration//GEN-END:variables
}
